#!/usr/bin/env bash
# -*- mode: sh -*-

current="$(tmux display-message -p '#S')"

tmux list-sessions -F '#S' | while read -r line; do
  if [[ "$line" != "$current" && "$line" =~ ^[[:digit:]]+$ ]]; then
    tmux kill-session -t "$line"
  fi
done
